In [11]:
import pandas as pd

In [12]:
person = pd.read_excel('../data/계약직 비율.xlsx')

In [13]:
person

            회사명  거래소코드     회계년도  기간제_기말인원  합계_기말인원
0      (주)CMG제약  58820  2011/12       0.0    135.0
1      (주)CMG제약  58820  2012/12       7.0    134.0
2      (주)CMG제약  58820  2013/12       0.0    136.0
3      (주)CMG제약  58820  2014/12       0.0    164.0
4      (주)CMG제약  58820  2015/12       9.0    156.0
...         ...    ...      ...       ...      ...
17482   흥구석유(주)  24060  2018/12      49.0     84.0
17483   흥구석유(주)  24060  2019/12      42.0     79.0
17484   흥구석유(주)  24060  2020/12      35.0     68.0
17485   흥구석유(주)  24060  2021/12      37.0     71.0
17486   흥구석유(주)  24060  2022/12      37.0     69.0

[17487 rows x 5 columns]

In [14]:
person['기간제비율'] = person.groupby(['회사명', '회계년도'])['기간제_기말인원'].transform(lambda x: x / person['합계_기말인원'] * 100)

In [15]:
person['기간제비율'] = person['기간제비율'].round(2)

In [16]:
person['회계년도'] =pd.to_datetime(person['회계년도'],format='%Y/%m')

In [19]:
person = person[['회사명','거래소코드','회계년도','기간제비율']]

In [20]:
main_df = pd.read_excel('./메인데이터프레임2.xlsx',index_col=0)
main_df

,회사명,시장종류,거래소코드,회계년도,상장일,label,평균근속연수,설립일,주거래은행,R&D 비용,업력,임원진 주식 보유,최대주주변경 횟수,감사법인 변경 횟수,수출기업여부,직원수 증감
0,(주)CMG제약,kosdaq,58820,2011-12-01,2001-08-31,0,3년8개월,2001/08/01,KEB하나은행,3.08,10,0.00,0,0,0,4.65
1,(주)CMG제약,kosdaq,58820,2012-12-01,2001-08-31,0,2.9,2001/08/01,KEB하나은행,2.58,11,0.00,1,0,0,-0.74
2,(주)CMG제약,kosdaq,58820,2013-12-01,2001-08-31,0,3.94,2001/08/01,KEB하나은행,31.98,12,0.00,1,0,1,1.49
3,(주)CMG제약,kosdaq,58820,2014-12-01,2001-08-31,0,2.69,2001/08/01,KEB하나은행,18.64,13,0.00,1,0,1,20.59
4,(주)CMG제약,kosdaq,58820,2015-12-01,2001-08-31,0,3.31,2001/08/01,KEB하나은행,22.22,14,0.00,1,1,1,-4.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17482,흥구석유(주),kosdaq,24060,2018-12-01,1994-12-07,0,6.02,1966/12/16,DGB대구은행,NaN,24,33.09,3,2,0,-9.68
17483,흥구석유(주),kosdaq,24060,2019-12-01,1994-12-07,0,6.23,1966/12/16,DGB대구은행,NaN,25,31.19,3,2,0,-5.95
17484,흥구석유(주),kosdaq,24060,2020-12-01,1994-12-07,0,7.54,1966/12/16,DGB대구은행,NaN,26,29.86,3,3,0,-13.92
17485,흥구석유(주),kosdaq,24060,2021-12-01,1994-12-07,0,7.61,1966/12/16,DGB대구은행,NaN,27,29.86,3,3,0,4.41
17486,흥구석유(주),kosdaq,24060,2022-12-01,1994-12-07,0,7.8,1966/12/16,DGB대구은행,NaN,28,29.86,3,3,0,-2.82

In [21]:
main_df = pd.merge(left=main_df,right=person,on=['회사명','거래소코드','회계년도'],how='left')

In [23]:
main_df.to_excel('./비재무 메인 데이터.xlsx')