In [1]:
import pandas as pd

In [3]:
df = pd.read_excel('./메인 데이터 프레임2.xlsx')
df = df.drop(['Unnamed: 0.1','Unnamed: 0'],axis=1)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17487 entries, 0 to 17486
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   회사명          17487 non-null  object
 1   시장종류         17487 non-null  object
 2   거래소코드        17487 non-null  int64
 3   회계년도         17487 non-null  datetime64[ns]
 4   상장일          17487 non-null  datetime64[ns]
 5   label        15896 non-null  object
 6   평균근속연수       14449 non-null  object
 7   설립일          17487 non-null  object
 8   주거래은행        17474 non-null  object
 9   R&D 비용       11715 non-null  float64
 10  최대주주변경 횟수    17487 non-null  int64
 11  임원진 주식 보유비율  17487 non-null  float64
 12  업력           17487 non-null  int64
dtypes: datetime64[ns](2), float64(2), int64(3), object(6)
memory usage: 1.7+ MB

In [36]:
df

,Unnamed: 0,회사명,시장종류,거래소코드,회계년도,상장일,label,평균근속연수,설립일,주거래은행,R&D 비용,최대주주변경 횟수,임원진 주식 보유비율
0,0,(주)CMG제약,kosdaq,58820,2011/12,2001/08/31,0,3년8개월,2001/08/01,KEB하나은행,3.08,0,0.00
1,1,(주)CMG제약,kosdaq,58820,2012/12,2001/08/31,0,2.9,2001/08/01,KEB하나은행,2.58,1,0.00
2,2,(주)CMG제약,kosdaq,58820,2013/12,2001/08/31,0,3.94,2001/08/01,KEB하나은행,31.98,1,0.00
3,3,(주)CMG제약,kosdaq,58820,2014/12,2001/08/31,0,2.69,2001/08/01,KEB하나은행,18.64,1,0.00
4,4,(주)CMG제약,kosdaq,58820,2015/12,2001/08/31,0,3.31,2001/08/01,KEB하나은행,22.22,1,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17482,17482,흥구석유(주),kosdaq,24060,2018/12,1994/12/07,0,6.02,1966/12/16,DGB대구은행,NaN,7,5.51
17483,17483,흥구석유(주),kosdaq,24060,2019/12,1994/12/07,0,6.23,1966/12/16,DGB대구은행,NaN,8,5.20
17484,17484,흥구석유(주),kosdaq,24060,2020/12,1994/12/07,0,7.54,1966/12/16,DGB대구은행,NaN,9,4.98
17485,17485,흥구석유(주),kosdaq,24060,2021/12,1994/12/07,0,7.61,1966/12/16,DGB대구은행,NaN,10,4.98
17486,17486,흥구석유(주),kosdaq,24060,2022/12,1994/12/07,0,7.8,1966/12/16,DGB대구은행,NaN,11,4.98

In [37]:
from datetime import datetime

In [38]:
# 회계년도와 상장일 컬럼의 데이터를 시계열 형식으로 변환
df['회계년도'] = pd.to_datetime(df['회계년도'], format='%Y/%m')
df['상장일'] = pd.to_datetime(df['상장일'], format='%Y/%m/%d')

In [39]:
# 회계년도에서 상장일을 뺀 값을 계산하여 새로운 컬럼인 '업력'을 생성
df['업력'] = (df['회계년도'] - df['상장일']).dt.days

In [40]:
# '업력' 컬럼에 저장된 값은 일단위로 되어있음-> 연도 단위로 변경
df['업력'] = df['업력'] // 365

In [41]:
df

,Unnamed: 0,회사명,시장종류,거래소코드,회계년도,상장일,label,평균근속연수,설립일,주거래은행,R&D 비용,최대주주변경 횟수,임원진 주식 보유비율,업력
0,0,(주)CMG제약,kosdaq,58820,2011-12-01,2001-08-31,0,3년8개월,2001/08/01,KEB하나은행,3.08,0,0.00,10
1,1,(주)CMG제약,kosdaq,58820,2012-12-01,2001-08-31,0,2.9,2001/08/01,KEB하나은행,2.58,1,0.00,11
2,2,(주)CMG제약,kosdaq,58820,2013-12-01,2001-08-31,0,3.94,2001/08/01,KEB하나은행,31.98,1,0.00,12
3,3,(주)CMG제약,kosdaq,58820,2014-12-01,2001-08-31,0,2.69,2001/08/01,KEB하나은행,18.64,1,0.00,13
4,4,(주)CMG제약,kosdaq,58820,2015-12-01,2001-08-31,0,3.31,2001/08/01,KEB하나은행,22.22,1,0.00,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17482,17482,흥구석유(주),kosdaq,24060,2018-12-01,1994-12-07,0,6.02,1966/12/16,DGB대구은행,NaN,7,5.51,24
17483,17483,흥구석유(주),kosdaq,24060,2019-12-01,1994-12-07,0,6.23,1966/12/16,DGB대구은행,NaN,8,5.20,25
17484,17484,흥구석유(주),kosdaq,24060,2020-12-01,1994-12-07,0,7.54,1966/12/16,DGB대구은행,NaN,9,4.98,26
17485,17485,흥구석유(주),kosdaq,24060,2021-12-01,1994-12-07,0,7.61,1966/12/16,DGB대구은행,NaN,10,4.98,27
17486,17486,흥구석유(주),kosdaq,24060,2022-12-01,1994-12-07,0,7.8,1966/12/16,DGB대구은행,NaN,11,4.98,28