In [40]:
import pandas as pd

In [41]:
largest_shareholder = pd.read_excel('../data/최대주주변경횟수.xlsx')
largest_shareholder.head(10)

        회사명  거래소코드     회계년도     회계년월        성명
0  (주)CMG제약  58820  2011/12  2011/12       김원정
1  (주)CMG제약  58820  2011/12  2011/12       김원정
2  (주)CMG제약  58820  2012/12  2012/12  (주)차바이오텍
3  (주)CMG제약  58820  2012/12  2012/12  (주)차바이오텍
4  (주)CMG제약  58820  2013/12  2013/12  (주)차바이오텍
5  (주)CMG제약  58820  2013/12  2013/12  (주)차바이오텍
6  (주)CMG제약  58820  2014/12  2014/12  (주)차바이오텍
7  (주)CMG제약  58820  2014/12  2014/12  (주)차바이오텍
8  (주)CMG제약  58820  2015/12  2015/12  (주)차바이오텍
9  (주)CMG제약  58820  2015/12  2015/12  (주)차바이오텍

In [42]:
largest_shareholder.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113306 entries, 0 to 113305
Data columns (total 5 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   회사명     113306 non-null  object
 1   거래소코드   113306 non-null  int64
 2   회계년도    113306 non-null  object
 3   회계년월    110549 non-null  object
 4   성명      110549 non-null  object
dtypes: int64(1), object(4)
memory usage: 4.3+ MB

In [43]:
largest_shareholder['성명'].fillna('', inplace=True)

In [44]:
largest_shareholder.loc[largest_shareholder['성명'].str.contains(r'((주)|연금|은행|기관|주식|회사|전자|홀딩스|골든|그룹|재단|투자|(사)|(유)|(재)|SK|sk|STIC|CO\.|케어|TETON|INC|갤러리|시큐리티|L.P.|PEF|펀드|알파조합|LLC|자산운용|조합|일자리창출펀드|원방테크|블루조합|Global Advisors|(학)|IT|파이낸셜|Inc.|N.V|NV|Group|Bio|반도체|GRANTOP|Emmaus|에스비아이인베스트먼트|GOLDEN|KoFC-WIP|디에이치코리아㈜|㈜|RESEARCH COMPANY|연구원|메리츠종합금융증권|엘지디스플레이|에스엠인더스트리|학원|F-M|Pte|Ltd|Financial)'), '성명'] = ''

C:\Users\kyaa0\AppData\Local\Temp\ipykernel_11188\3855877222.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  largest_shareholder.loc[largest_shareholder['성명'].str.contains(r'((주)|연금|은행|기관|주식|회사|전자|홀딩스|골든|그룹|재단|투자|(사)|(유)|(재)|SK|sk|STIC|CO\.|케어|TETON|INC|갤러리|시큐리티|L.P.|PEF|펀드|알파조합|LLC|자산운용|조합|일자리창출펀드|원방테크|블루조합|Global Advisors|(학)|IT|파이낸셜|Inc.|N.V|NV|Group|Bio|반도체|GRANTOP|Emmaus|에스비아이인베스트먼트|GOLDEN|KoFC-WIP|디에이치코리아㈜|㈜|RESEARCH COMPANY|연구원|메리츠종합금융증권|엘지디스플레이|에스엠인더스트리|학원|F-M|Pte|Ltd|Financial)'), '성명'] = ''

In [45]:
largest_shareholder.to_excel('기업제외 최대주주.xlsx')

In [124]:
df = pd.read_excel('./기업제외 최대주주.xlsx')

In [125]:
df

        Unnamed: 0       회사명  거래소코드     회계년도     회계년월       성명
0                0  (주)CMG제약  58820  2011/12  2011/12      김원정
1                1  (주)CMG제약  58820  2011/12  2011/12      김원정
2                2  (주)CMG제약  58820  2012/12  2012/12      NaN
3                3  (주)CMG제약  58820  2012/12  2012/12      NaN
4                4  (주)CMG제약  58820  2013/12  2013/12      NaN
...            ...       ...    ...      ...      ...      ...
113301      113301   흥구석유(주)  24060  2022/12  2022/12      서상덕
113302      113302   흥구석유(주)  24060  2022/12  2022/12      김도훈
113303      113303   흥구석유(주)  24060  2022/12  2022/12      김철희
113304      113304   흥구석유(주)  24060  2022/12  2022/12      성현지
113305      113305   흥구석유(주)  24060  2022/12  2022/12  김상우외 3인

[113306 rows x 6 columns]

In [126]:
df =df.drop(['Unnamed: 0'],axis=1)

In [127]:
df = df.drop_duplicates()

In [128]:
df

             회사명  거래소코드     회계년도     회계년월       성명
0       (주)CMG제약  58820  2011/12  2011/12      김원정
2       (주)CMG제약  58820  2012/12  2012/12      NaN
4       (주)CMG제약  58820  2013/12  2013/12      NaN
6       (주)CMG제약  58820  2014/12  2014/12      NaN
8       (주)CMG제약  58820  2015/12  2015/12      NaN
...          ...    ...      ...      ...      ...
113301   흥구석유(주)  24060  2022/12  2022/12      서상덕
113302   흥구석유(주)  24060  2022/12  2022/12      김도훈
113303   흥구석유(주)  24060  2022/12  2022/12      김철희
113304   흥구석유(주)  24060  2022/12  2022/12      성현지
113305   흥구석유(주)  24060  2022/12  2022/12  김상우외 3인

[89436 rows x 5 columns]

In [129]:
a = df.groupby(["회사명", "거래소코드", "회계년도"])["성명"].apply(set)

In [130]:
df_a = pd.DataFrame(a)

In [131]:
df_a

                                                        성명
회사명      거래소코드 회계년도
(주)CMG제약 58820 2011/12                               {김원정}
               2012/12                               {nan}
               2013/12                               {nan}
               2014/12                               {nan}
               2015/12                               {nan}
...                                                    ...
흥구석유(주)  24060 2018/12  {김상우, 김철희, 서상덕, 김도훈, 김상우외 3인, 성현지}
               2019/12  {김상우, 김철희, 서상덕, 김도훈, 김상우외 3인, 성현지}
               2020/12  {김상우, 김철희, 서상덕, 김도훈, 김상우외 3인, 성현지}
               2021/12  {김상우, 김철희, 서상덕, 김도훈, 김상우외 3인, 성현지}
               2022/12  {김상우, 김철희, 서상덕, 김도훈, 김상우외 3인, 성현지}

[17487 rows x 1 columns]

In [132]:
 #"다음년도_성명_변경여부" 컬럼을 생성하여 이전 컬럼과 한명이라도 최대 주주가 바뀌었는지 여부 확인
df_a['다음년도_성명_변경여부'] = (df_a['성명'] != df_a['성명'].shift(1))

In [133]:
df_a

                                                        성명  다음년도_성명_변경여부
회사명      거래소코드 회계년도
(주)CMG제약 58820 2011/12                               {김원정}          True
               2012/12                               {nan}          True
               2013/12                               {nan}         False
               2014/12                               {nan}         False
               2015/12                               {nan}         False
...                                                    ...           ...
흥구석유(주)  24060 2018/12  {김상우, 김철희, 서상덕, 김도훈, 김상우외 3인, 성현지}          True
               2019/12  {김상우, 김철희, 서상덕, 김도훈, 김상우외 3인, 성현지}         False
               2020/12  {김상우, 김철희, 서상덕, 김도훈, 김상우외 3인, 성현지}         False
               2021/12  {김상우, 김철희, 서상덕, 김도훈, 김상우외 3인, 성현지}         False
               2022/12  {김상우, 김철희, 서상덕, 김도훈, 김상우외 3인, 성현지}         False

[17487 rows x 2 columns]

In [134]:
df_a.loc[df_a.groupby(['회사명', '거래소코드']).head(1).index, '다음년도_성명_변경여부'] = False

In [136]:
# "회사명"과 "거래소코드"를 기준으로 그룹화하고, "다음년도_성명_변경여부"의 누적합을 구하여 "최대주주변경 횟수"를 계산
df_a['최대주주변경 횟수'] = df_a.groupby(['회사명', '거래소코드'])['다음년도_성명_변경여부'].cumsum()

In [138]:
df_a = df_a.reset_index()

In [140]:
df_a.to_excel('./최대주주 변경 최종.xlsx')